### ISSUE TITLE
title field in basic & advanced search should look on all forms of titles

### ISSUE THREAD

**Issue by roxannewyns** [libis/pa_cct#1]
**Title field in advanced and basic search should search on all forms of titles:**

- Title (preferred_label)
- Title in pinyin (to become a simple text field)
- Varying form of title (to become a simple text field)
- Abbreviated title (text field) --> is this possible when the field is no longer being displayed???

@aruijmen to provide display to Naeem for data visualisation and element codes to include in search

![image](https://user-images.githubusercontent.com/3798589/27286336-0c708c18-5500-11e7-9ebb-96f6400c19d3.png)

**Comment by naeemmuhammad** [comment]
Fixes:
877979fb9ed4c25dc0a384c712a25760f880708f
1e153a1c53104574aa9ac6e2bd11d7115250b5af
c5598f7e1761a0111b4d1a35182388b20be0c0b2
