### ISSUE TITLE
Display of new text fields for 'varying form of title' and 'title in pinyin'

### ISSUE THREAD

**Issue by roxannewyns** [libis/pa_cct#6]
These will become text fields instead of non-preferred label fields. See also #1 

@aruijmen provide display template
@naeemmuhammad implement on pawtucket

**Comment by naeemmuhammad** [comment]
Commits:
877979fb9ed4c25dc0a384c712a25760f880708f
1e153a1c53104574aa9ac6e2bd11d7115250b5af
