### ISSUE TITLE
title search in basic and advanced search

### ISSUE THREAD

**Issue by roxannewyns** [libis/pa_cct#8]
Remane 'Title' in 'Search all titles'
Add 3 separate title fields: 'Title', 'Pinyin Title' and 'Alternative Form of Title' so they can also pick this option. 

![image](https://user-images.githubusercontent.com/3798589/27951528-90667bd2-6305-11e7-89e4-274d88f31bfc.png)

**Comment by naeemmuhammad** [comment]
fix: https://github.com/libis/pa_cct/commit/dd11fa988de01ab54b4a3d0d8ddead1fcc4b4e24
